---
title: "Explainable expected goal"
author: "Piotr Szulc"
date: "2023-02-25"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE, 
  # fig.path = "figs/"
  fig.align = "center",
  out.width = "90%",
  fig.width = 6,
  fig.asp = 0.618
)
```

```{r}
library("tidyverse")
library("tidymodels")
library("ROSE")
library("DALEX")
library("ingredients")

shot_stats_all <- read_csv("raw_data.csv")

shot_stats_all <- shot_stats_all %>% 
  filter(result != "OwnGoal") %>%
  mutate(status = as.factor(ifelse(result == "Goal", 1, 0))) %>%
  mutate(distanceToGoal = sqrt((105 - (X * 105)) ^ 2 + (34 - (Y * 68)) ^ 2)) %>%
  mutate(angleToGoal = abs(atan((7.32 * (105 - (X * 105))) / 
      ((105 - (X * 105))^2 + (34 - (Y * 68)) ^ 2 - (7.32 / 2) ^ 2)) * 180 / pi)) %>%
  mutate(h_a = factor(h_a),
    situation = factor(situation),
    shotType = factor(shotType),
    lastAction = factor(lastAction),
    minute = as.numeric(minute)) %>%
  select(status, minute, h_a, situation, shotType, lastAction, 
    distanceToGoal, angleToGoal, league, season, match_id, result, player_id)

shot_stats <- shot_stats_all %>%
  select(status, minute, h_a, situation, shotType, lastAction, 
    distanceToGoal, angleToGoal)

set.seed(123)
split <- initial_split(shot_stats, prop = 0.5, strata = status)
shot_train <- training(split)
shot_test <- testing(split)
```

## Original data

```{r}
rf_model <- rand_forest(mtry = 2, min_n = 50, trees = 1000)  %>% 
  set_mode("classification") %>% 
  set_engine("ranger", splitrule = "extratrees", importance = "impurity")
# splitrule = "extratrees" --> Extremely Randomized Trees

rf_recipe <- recipe(status ~ ., shot_train)

rf_wflow <- workflow() %>%
  add_model(rf_model) %>%
  add_recipe(rf_recipe)

rf_fit <- rf_wflow %>% 
  fit(shot_train)

rf_fit %>% 
  extract_fit_engine() %>%
  vip::vip()

results <- shot_test %>% 
  add_column(predict(rf_fit, shot_test)) %>% 
  add_column(predict(rf_fit, shot_test, type = "prob"))
accuracy(results, status, .pred_class) # 0.904
roc_auc(results, status, .pred_0) # 0.810
```

## Oversampling

```{r}
set.seed(42)
shot_train_over <- ovun.sample(status ~ ., data = shot_train, method = "over")$data

rf_fit_over <- rf_wflow %>% 
  fit(shot_train_over)

results <- shot_test %>% 
  add_column(predict(rf_fit_over, shot_test)) %>% 
  add_column(predict(rf_fit_over, shot_test, type = "prob"))
accuracy(results, status, .pred_class) # 0.791
roc_auc(results, status, .pred_0) # 0.809
```

## Undersampling

You can increase the ratio in `initial_split()`, but this does not change the results.

```{r}
set.seed(42)
shot_train_under <- ovun.sample(status ~ ., data = shot_train, method = "under")$data

rf_fit_under <- rf_wflow %>% 
  fit(shot_train_under)

results <- shot_test %>% 
  add_column(predict(rf_fit_under, shot_test)) %>% 
  add_column(predict(rf_fit_under, shot_test, type = "prob"))
accuracy(results, status, .pred_class) # 0.757
roc_auc(results, status, .pred_0) # 0.808
```

## Explain

```{r fig.asp = 1}
model <- rf_fit %>% extract_fit_engine()
ranger_explained <- explain(model, data = shot_test)

## Teams

selected_observations_schalke <- shot_stats_all %>%
  filter(h_a == "h", match_id == 15298)
selected_observations_bayern <- shot_stats_all %>%
  filter(h_a == "a", match_id == 15298)

cp_schalke <- ceteris_paribus(ranger_explained, selected_observations_schalke)
cp_bayern  <- ceteris_paribus(ranger_explained, selected_observations_bayern)
cp_schalke$`_label_` <- "Schalke 04"
cp_bayern$`_label_` <- "Bayern Munich"

ap_dtg_schalke <- aggregate_profiles(cp_schalke, variables = "angleToGoal")
ap_dtg_bayern  <- aggregate_profiles(cp_bayern, variables = "angleToGoal")
plot(ap_dtg_schalke, ap_dtg_bayern)

## Players

selected_observations_by <- shot_stats_all %>%
  filter(player_id == 8637, season == 2020)
selected_observations_lm <- shot_stats_all %>%
  filter(player_id == 2097, season == 2020)
selected_observations_rl <- shot_stats_all %>%
  filter(player_id == 227, season == 2020)

cp_by <- ceteris_paribus(ranger_explained, selected_observations_by)
cp_lm <- ceteris_paribus(ranger_explained, selected_observations_lm)
cp_rl <- ceteris_paribus(ranger_explained, selected_observations_rl)
cp_by$`_label_` <- "Burak Yilmaz"
cp_lm$`_label_` <- "Lionel Messi"
cp_rl$`_label_` <- "Robert Lewandowski"

ap_dtg_by <- aggregate_profiles(cp_by, variables = "angleToGoal")
ap_dtg_lm <- aggregate_profiles(cp_lm, variables = "angleToGoal")
ap_dtg_rl <- aggregate_profiles(cp_rl, variables = "angleToGoal")
plot(ap_dtg_by, ap_dtg_lm, ap_dtg_rl)
```
